### ISSUE TITLE
Wiki PNG/GIF file

### ISSUE THREAD

**Issue by ChoiHyungKyu** [banksemi/Gachon-Village#110]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/44195740/49694729-d3357500-fbd2-11e8-9551-39662475fec5.gif)
![1](https://user-images.githubusercontent.com/44195740/49694733-ea746280-fbd2-11e8-9ac8-aaabb02919ad.png)

**Comment by ChoiHyungKyu** [comment]
![1](https://user-images.githubusercontent.com/44195740/49695069-6e7d1900-fbd8-11e8-828b-0554fc171f89.png)
![2](https://user-images.githubusercontent.com/44195740/49695070-7210a000-fbd8-11e8-8785-274cf83f8128.png)

**Comment by ChoiHyungKyu** [comment]
![2](https://user-images.githubusercontent.com/44195740/49695190-8fdf0480-fbda-11e8-8de2-72cc2629b1cd.png)

**Comment by ChoiHyungKyu** [comment]
![2-2](https://user-images.githubusercontent.com/44195740/49695222-1b589580-fbdb-11e8-8ce9-4e7abe2ebb6f.png)
![2-1](https://user-images.githubusercontent.com/44195740/49695223-1b589580-fbdb-11e8-9bae-d7283a1eea1e.png)

**Comment by ChoiHyungKyu** [comment]
![ezgif-4-3b377b0e0b19](https://user-images.githubusercontent.com/44195740/49695680-ff0c2700-fbe1-11e8-993f-8ca34a8cd147.gif)

**Comment by ChoiHyungKyu** [comment]
![default](https://user-images.githubusercontent.com/44195740/49695811-b05f8c80-fbe3-11e8-923f-09eae1bca6ba.png)

**Comment by ChoiHyungKyu** [comment]
![333](https://user-images.githubusercontent.com/44195740/49695890-e94c3100-fbe4-11e8-8722-3b13479d8590.png)

**Comment by ChoiHyungKyu** [comment]
![dddfff](https://user-images.githubusercontent.com/44195740/49695935-8d35dc80-fbe5-11e8-8bfb-4904a93abcb4.png)

**Comment by ChoiHyungKyu** [comment]
![ezgif-4-c3c99a4ba3f2](https://user-images.githubusercontent.com/44195740/49696150-d50a3300-fbe8-11e8-9519-d3b2d70fc6d5.gif)

**Comment by banksemi** [comment]
![그림1](https://user-images.githubusercontent.com/17453822/59479672-cd2d9300-8e98-11e9-99bd-f99dae08215c.png)
