### ISSUE TITLE
How will we design a game? (include GUI)

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#13]
3 Images In-Game
![kakaotalk_20181028_185025998](https://user-images.githubusercontent.com/17453822/47616512-23fc7d00-db01-11e8-94e6-285882c729ab.png)
![kakaotalk_20181028_185052577](https://user-images.githubusercontent.com/17453822/47616513-23fc7d00-db01-11e8-8650-89661ad520a4.png)
![kakaotalk_20181028_185116817](https://user-images.githubusercontent.com/17453822/47616514-23fc7d00-db01-11e8-894a-f92a365886de.png)

**Comment by banksemi** [comment]
This is my idea of layout.
It can be changed at any time.

![image](https://user-images.githubusercontent.com/17453822/47727147-39a7a900-dc9f-11e8-9792-82dda4dfe9e0.png)

**Comment by ChoiHyungKyu** [comment]
<hr>
<h3>MAP(M) IMG & Assignment(Like Quest) & Chat</h3>
<hr>
![gavi](https://user-images.githubusercontent.com/44195740/47785405-f9eacb00-dd4b-11e8-851e-9fd244fa64d3.png)

<hr>

It seems like to SeungHwa's. But If we push button 'M', We can show Giant Map and Quest Line(Homework, Team Project)

And Chatting System,
We can see All dialog, seperated dialog, ...

I think At 1st version, we should make character image same.
