### ISSUE TITLE
Make a Game Title for Login Scene

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#16]
Use copyright-free images.
https://pixabay.com/ko/%EC%88%B2-%EA%B4%91%EC%84%A0-%EC%95%88%EA%B0%9C-%EC%9E%90%EC%97%B0-%EB%82%98%EB%AC%B4-%EB%B9%94-%EA%B4%91-%EA%B7%BC-67286/

https://pixabay.com/en/forest-rays-fog-nature-trees-beam-67286/

This is an example of a project that we've done before. (2013 - 2016)

![image](https://user-images.githubusercontent.com/17453822/47913691-5c74d000-dee0-11e8-86f0-0fa4087131c4.png)

**Comment by EunAhChoi** [comment]
How about Christmas atmosphere ????
I love Christmas very much
