### ISSUE TITLE
Board contents are not enter!

### ISSUE THREAD

**Issue by EunAhChoi** [banksemi/Gachon-Village#24]
![image](https://user-images.githubusercontent.com/44494200/47961543-5998ed00-e050-11e8-876a-ebbf3126bf17.png)

Like above, between string and string, there is no enter!
help me~~~~~

**Comment by banksemi** [comment]
ok~~~~~~ wait!

**Comment by banksemi** [comment]
Read innerHtml instead of innerText.


</p> </div> </tr> -> Enter

</td> -> Space
Else Tag ... <td> <tr> -> Ignore

**Comment by EunAhChoi** [comment]
OKAY  I'll give a try!!

**Comment by EunAhChoi** [comment]
![image](https://user-images.githubusercontent.com/44494200/48013719-45481380-e168-11e8-83c8-ba0861cfd771.png)


Seems to have been resolved !!!!!!

Please check :)
