### ISSUE TITLE
If board type is Homework, The time and publisher do not appear.

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#40]
But How about making this content(commit) better?

If board type is Homework, The time and publisher do not appear.

There is no problem yet, but there may be a problem when applying the database because the value is NULL.

So I propose **two features**.
1. Each GachonClass gets information (professor or sisap).
2. Set the publisher to the above information and Set the Time to DateTime.Now.

If you don't like the entry in 1, it would be good to set publisher to "Admin."

_Originally posted by @banksemi in https://github.com/banksemi/Gachon-Village/pull/38/comment#issuecomment-437679581_

**Comment by EunAhChoi** [comment]
OK! I did it   Thanks
Close #40
