### ISSUE TITLE
SQL Library

### ISSUE THREAD

**Issue by EunAhChoi** [banksemi/Gachon-Village#45]
![image](https://user-images.githubusercontent.com/44494200/48389089-5502c180-e73f-11e8-9b91-5aa8897a9b21.png)

Like above, It is very inconvenient to use SQL

Let's make SQL Library to use SQL string more convenient.

**Comment by banksemi** [comment]
[New branch](/banksemi/Gachon-Village/tree/issue/45-SQL-Library)
