### ISSUE TITLE
Screenshot of our Village!

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#57]
![1](https://user-images.githubusercontent.com/17453822/48794545-aad9f980-ed3d-11e8-96f9-326b4491833b.png)
![2](https://user-images.githubusercontent.com/17453822/48794548-aca3bd00-ed3d-11e8-9e43-6cf359ffe488.png)
![3](https://user-images.githubusercontent.com/17453822/48794560-b5948e80-ed3d-11e8-8bc3-fa891e6fb2d6.png)
![4](https://user-images.githubusercontent.com/17453822/48794563-b6c5bb80-ed3d-11e8-833e-1d2753e980e0.png)
![5](https://user-images.githubusercontent.com/17453822/48794567-b9281580-ed3d-11e8-956d-0f83c59c3e4f.png)
![6](https://user-images.githubusercontent.com/17453822/48794577-bf1df680-ed3d-11e8-95e4-4cffe200caf4.png)
![7](https://user-images.githubusercontent.com/17453822/48794590-c80ec800-ed3d-11e8-9331-0e95ed2a6c7a.png)

**Comment by banksemi** [comment]
# This is User Interface
![image](https://user-images.githubusercontent.com/17453822/48794735-263bab00-ed3e-11e8-9855-c863e102a3e5.png)

**Comment by EunAhChoi** [comment]
kkkkkk perfect👏👏  Gachon village is very exciting

**Comment by banksemi** [comment]
Very good. goodbye~! @EunAhChoi 
Next time, let's take a screenshot with the team.
