### ISSUE TITLE
In the keyword system, Check invalid user input

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#77]
Please consider the following situations:

Console.WriteLine(KeywordSystem.test("[Network Homework", "Network Programming","Homework"));

Why:
Of course this is incorrect input data, but the user can make this mistake enough.
However, if the server fails with an error, the entire program stops. 
That means "server don't trust the user's input".

_Originally posted by @banksemi in https://github.com/banksemi/Gachon-Village/issues/67#issuecomment-441403322_

**Comment by EunAhChoi** [comment]
It was part of what I expected.......:(
I'll fix it soon.
Maybe, Today
