### ISSUE TITLE
What about the dice(random value) function using chat?

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#80]
For example, if the user enters "/dice" using chat, the system informs everyone of the results.

"~~~(user) rolled the dice and got 4!"
It's simple, but it'll be fun.

**Comment by banksemi** [comment]
> Is the random function in C # similar to java?
> Then I think I can!!

Ok, 

Random function in C# is easy.

public static Random rd = new Random();
int data = rd.Next(min number, max number);

**Comment by EunAhChoi** [comment]
![kakaotalk_20181128_205838700](https://user-images.githubusercontent.com/44494200/49150568-a40c4180-f350-11e8-8f37-c5bd71ac2395.png)

HAHAHA   I win~~~~~~~~~~~!

**Comment by banksemi** [comment]
![image](https://user-images.githubusercontent.com/17453822/49150556-98207f80-f350-11e8-8c65-ffa9094d05a8.png)
She ran away.

Therefore, I won!!!!!!!!! 👍
