### ISSUE TITLE
Whisper for the same name

### ISSUE THREAD

**Issue by EunAhChoi** [banksemi/Gachon-Village#87]
If we have a student with the same name
Whispers will be difficult to distinguish because they allow you to send them by name.
We need a key to distinguish it.

**Comment by banksemi** [comment]
This is one way.
Add a new function to your Gachon library.

This function returns the student's ID based on the input data.


Input data can sometimes be:
"Lee Seung Hwa," "17 Lee Seung Hwa," "201735861" and "201735861 Lee Seung Hwa"

For each case, separate the name or class.

Then, based on the data that you detach, use MYSQL WHERE to get a single ID.

(If more than one exists, an error)
