### ISSUE TITLE
Finish the study function

### ISSUE THREAD

**Issue by banksemi** [banksemi/Gachon-Village#89]
The following functions must be completed in order!

The deadline is today 30!

- [x] Recording Chatting Data (each group)
- [x] Creating a study (sign up)
- [x] Creating a study window - tab.
- [x] Creating a study window - main.
- [x] Creating a study window - members list.
- [ ] Creating a study window - file share.
- [x] Creating a study window - save chatting.

File sharing is an important feature, but I don't have time.

**Comment by banksemi** [comment]
Study Window
![image](https://user-images.githubusercontent.com/17453822/49275500-d3d95780-f4be-11e8-9cdd-73e538c32cbf.png)

**Comment by EunAhChoi** [comment]
Did a lot.
amazing.........!

**Comment by EunAhChoi** [comment]
In the study in Gachon Village, I succeeded in storing the contents of the study conversation.

![image](https://user-images.githubusercontent.com/44494200/49309886-0bc4b700-f520-11e8-8b8b-b022677dc3c7.png)
