### ISSUE TITLE
create database view group_file_info

### ISSUE THREAD

**Issue by EunAhChoi** [banksemi/Gachon-Village#96]
select group_name, A.file_no, upload_user, C.name as upload_user_name, upload_date, B.
name, size, owner, D.name as owner_name, `date`
from group_file as A join `file` as B join account as C join account as D
on (A.file_no = B.file_no and A.upload_user = C.id and B.owner = D.id);

**Comment by banksemi** [comment]
Ok
I checked your SQL and commit to master branch!
Now, We can show file's owner name in Files Tab in Study Window.
